### ISSUE TITLE
Recherche USK, Lizenzen, Gema

### ISSUE THREAD

**Issue by betuelkabakulak** [rtetic/EasyGames#11]
Welche Anforderungen für GoT benötigt werden in Bezug auf FSK, Lizenzen, Gema

**Comment by betuelkabakulak** [comment]
Bis zum 22.10.2018

**Comment by JulianLange** [comment]
USK: (="FSK für spiele")
Kosten:
http://www.usk.de/extramenue/login/publisher/material/kostenordnung/
Leitkriterien
http://www.usk.de/fileadmin/documents/Publisher_Bereich/2016-06-10%20Leitkriterien%20USK.pdf

Prüfdauer: 5-20 Werktage; Spiel muss vollständig sein (auch weitgehend bugfrei); Nicht verpflichtend, falls keine Jugendfreigabe; 
Keine verpflichtende Prüfung in USA, Großteil von Europa
Consulting möglich (siehe Kosten), allerdings keine verbindliche Voreinschätzung
