### ISSUE TITLE
Konfiguration des Tools

### ISSUE THREAD

**Issue by betuelkabakulak** [rtetic/EasyGames#12]

**Comment by betuelkabakulak** [comment]
Wie verwenden wir GitHub "sauber"?

**Comment by betuelkabakulak** [comment]
Labels bearbeiten

**Comment by JulianLange** [comment]
"Projects" in Github also Sprints: 
+ keine Extension notwendig
- nur Kanban-Board
- nicht besonders schön

Zenhub
+ Zusätzlich zu Kanbab-Board auch Burndown Charts und andere Analyse-Tools
+ schöner gestaltet
- zusätuliche Extension
